### ISSUE TITLE
关于解包以后的工作的方向

### ISSUE THREAD

**Issue by MotokaJuu** [nijinekoyo/Gakuen-idolmaster-ab-decrypt#1]
感谢作者，现在已经解包完成，但是解包得到的asset_bundle都没有后缀。我想问问如果想要得到人物的模型以及贴图文件的话接下来需要用什么工具和要怎样做，谢谢。

**Comment by nijinekoyo** [comment]
使用AssetStudio解开ab包就行了

**Comment by MotokaJuu** [comment]
十分感谢
