### ISSUE TITLE
关于APK解包

### ISSUE THREAD

**Issue by chihya72** [nijinekoyo/Gakuen-idolmaster-ab-decrypt#2]
请问一下作者可以尝试一下APK包体内的octodb解包吗，尝试了一下直接用您decrypt/octodb来解APK内的好像失败了

**Comment by nijinekoyo** [comment]
APK内的文件就包含在`/data/data/com.bandainamcoent.idolmaster_gakuen/files/octo`目录的文件里面
例如`assets/Octo/1/41343231`文件，其MD5值为`84c0a36d9322372004088d11114016d8`，对应的就是`octo/v1/400/1/41343231/84c0a36d9322372004088d11114016d8"`文件

**Comment by chihya72** [comment]
原来如此！谢谢您！那想问一下像成就和技能卡那些的文本也是在assetstudio里直接找到吗

**Comment by nijinekoyo** [comment]
我也不是很确定文本资产的位置，只知道部分文本资产可以在resource里面找到

**Comment by Woodman3** [comment]
> 原来如此！谢谢您！那想问一下像成就和技能卡那些的文本也是在assetstudio里直接找到吗

大佬有找到技能卡的文本和效果是在哪里存放的吗
