### ISSUE TITLE
Is it possible to pack and encrypt back the files?

### ISSUE THREAD

**Issue by ufalsalman** [nijinekoyo/Gakuen-idolmaster-ab-decrypt#3]
Hello. I was thinking of doing a little bit of translation mod for Gakumas. I was able to decrypt, extract and view the files inside with the script and AssetStudio. I'm wonder if there's any possible to pack and encrypt them back? What kind of requirements if there's a way to do that? Thanks.

**Comment by nijinekoyo** [comment]
I am also interested in repackaging. According to my current investigation, some plot texts are saved as text files in the `txt` format. Most of them do not encrypt the files. You just need to modify them and then correct `octocacheevai`.

So it is enough to encrypt and package `octocacheevai`, but I am not sure whether the game will check whether the `octocacheevai` file is consistent with the cloud. This requires more information.

**Comment by nijinekoyo** [comment]
For the specific encryption method, you can refer to the decryption code implementation at [decrypt/octodb.py#L19](https://github.com/nijinekoyo/Gakuen-idolmaster-ab-decrypt/blob/main/decrypt/octodb.py#L19), which is standard AES encryption

**Comment by ufalsalman** [comment]
Thank you for the information. I'll try it first.
