### ISSUE TITLE
导出文件资产时产生：缓冲区空间不足错误

### ISSUE THREAD

**Issue by kanon511** [nijinekoyo/Gakuen-idolmaster-ab-decrypt#4]
在运行export_asset_bundle.py文件进行资产导出时，产生了多个类似
Error during the parsing of object -5248921323855943590
unpack_from requires a buffer of at least 7929252 bytes for unpacking 4 bytes at offset 7929248 (actual buffer size is 7929248)
的错误，请问是在使用过程中有什么操作错误吗，使用的源文件是当前8.21的最新游戏版本。
![image](https://github.com/user-attachments/assets/94785471-142c-4eee-b7f8-5e2a7594ea06)

然后关于人工补齐版本号，貌似该项目没有配置文件，也没找到如何导入版本号的方法。本人对于解包这方面不太了解，能麻烦告诉我如何导入版本号吗。

**Comment by nijinekoyo** [comment]
这个报错是正常的，部分资源确实无法被UnityPY解析
补齐版本号的说明是针对使用AS导出的，使用脚本时，脚本会自动补全版本号
